import { cachePrefix, resolveConfig, type ServiceWorkerConfig } from './config';

/**
 * Generate the source of a PWA service worker (`service-worker.js`) from config.
 *
 * The emitted SW implements the FIXED caching model (the one katalogos-web
 * converged on after the 2026-06-11 stale-menu fix):
 * - Public API reads: NETWORK-FIRST — always fetch fresh when online; the cached
 *   copy is only an offline fallback. This guarantees an edit/activation is
 *   reflected on the next load for every visitor (the old stale-while-revalidate
 *   served up to a day-old payload).
 * - Static assets: cache-first.
 * - Admin/auth API: network-only (never cached).
 * - A `{ type: <purgeMessageType>, externalId? }` message evicts cached public
 *   responses immediately (so an editor preview refreshes mid-session).
 * - Cache names are versioned; the activate handler deletes prefix-matching old
 *   versions so bumping the version evicts stale entries on deploy.
 *
 * The output is a plain ES5-style worker string with no imports — safe to write
 * straight into an app's `public/service-worker.js`.
 */
export function generateServiceWorker(config: ServiceWorkerConfig): string {
  const resolved = resolveConfig(config);
  const apiPrefix = cachePrefix(resolved.apiCacheName);
  const staticPrefix = cachePrefix(resolved.staticCacheName);

  const json = (value: unknown): string => JSON.stringify(value);

  return `/**
 * Service Worker — GENERATED by @dloizides/pwa-sw. DO NOT EDIT BY HAND.
 * Regenerate via the app's "generate:sw" script (config: pwa-sw.config.js).
 *
 * Caching strategies:
 * - Public API reads (network-first): always fresh when online; cache is an
 *   offline fallback only — so an edit/activation shows on the next load.
 * - Static assets (cache-first).
 * - Admin/auth API (network-only, never cached).
 * Cache names are versioned; bumping a version evicts the old (stale) cache on
 * activation. A "${resolved.purgeMessageType}" message evicts the public cache
 * immediately for same-session freshness.
 */

var API_CACHE = ${json(resolved.apiCacheName)};
var STATIC_CACHE = ${json(resolved.staticCacheName)};
var MANAGED_CACHES = [API_CACHE, STATIC_CACHE];
var API_CACHE_PREFIX = ${json(apiPrefix)};
var STATIC_CACHE_PREFIX = ${json(staticPrefix)};
var PUBLIC_API_MATCHERS = ${json(resolved.publicApiPathMatchers)};
var STATIC_EXTENSIONS = ${json(resolved.staticExtensions)};
var PURGE_MESSAGE_TYPE = ${json(resolved.purgeMessageType)};

/** A cacheable public API read (network-first) if its pathname matches any matcher. */
function isPublicApiRequest(url) {
  var pathname = new URL(url).pathname;
  for (var i = 0; i < PUBLIC_API_MATCHERS.length; i++) {
    if (pathname.indexOf(PUBLIC_API_MATCHERS[i]) !== -1) return true;
  }
  return false;
}

/** An admin/protected/auth request that must never be cached. */
function isAdminApiRequest(url) {
  var pathname = new URL(url).pathname;
  if (pathname.indexOf('/api/') !== -1 && pathname.indexOf('/public/') === -1) return true;
  if (pathname.indexOf('/realms/') !== -1 || pathname.indexOf('/token') !== -1) return true;
  return false;
}

/** A static asset (cache-first) based on file extension. */
function isStaticAsset(url) {
  var pathname = new URL(url).pathname.toLowerCase();
  for (var i = 0; i < STATIC_EXTENSIONS.length; i++) {
    if (pathname.lastIndexOf(STATIC_EXTENSIONS[i]) === pathname.length - STATIC_EXTENSIONS[i].length) return true;
  }
  return false;
}

/**
 * Network-first for public API: always try the network so edits show
 * immediately; cache successful responses for offline; only fall back to the
 * cached copy when the network fails.
 */
function networkFirst(event) {
  event.respondWith(
    caches.open(API_CACHE).then(function(cache) {
      return fetch(event.request).then(function(networkResponse) {
        if (networkResponse && networkResponse.ok) {
          var responseToCache = networkResponse.clone();
          var headers = new Headers(responseToCache.headers);
          headers.set('sw-cached-at', new Date().toISOString());
          return responseToCache.blob().then(function(body) {
            cache.put(event.request, new Response(body, {
              status: responseToCache.status,
              statusText: responseToCache.statusText,
              headers: headers,
            }));
            return networkResponse;
          });
        }
        return networkResponse;
      }).catch(function() {
        return cache.match(event.request);
      });
    })
  );
}

/** Cache-first for static assets. */
function cacheFirst(event) {
  event.respondWith(
    caches.open(STATIC_CACHE).then(function(cache) {
      return cache.match(event.request).then(function(cachedResponse) {
        if (cachedResponse) return cachedResponse;
        return fetch(event.request).then(function(networkResponse) {
          if (networkResponse && networkResponse.ok) {
            cache.put(event.request, networkResponse.clone());
          }
          return networkResponse;
        });
      });
    })
  );
}

/**
 * Evict cached public-API responses. With no externalId, drops the whole API
 * cache; with one, only entries whose URL contains that id.
 */
function purgePublicCache(externalId) {
  return caches.open(API_CACHE).then(function(cache) {
    if (!externalId) {
      return caches.delete(API_CACHE);
    }
    return cache.keys().then(function(requests) {
      return Promise.all(
        requests
          .filter(function(request) { return request.url.indexOf(externalId) !== -1; })
          .map(function(request) { return cache.delete(request); })
      );
    });
  });
}

// --- Lifecycle ---

self.addEventListener('install', function() {
  self.skipWaiting();
});

self.addEventListener('activate', function(event) {
  event.waitUntil(
    caches.keys().then(function(cacheNames) {
      return Promise.all(
        cacheNames
          .filter(function(name) {
            var isOurCache = name.indexOf(API_CACHE_PREFIX) === 0 || name.indexOf(STATIC_CACHE_PREFIX) === 0;
            var isCurrent = MANAGED_CACHES.indexOf(name) !== -1;
            return isOurCache && !isCurrent;
          })
          .map(function(name) { return caches.delete(name); })
      );
    }).then(function() {
      return self.clients.claim();
    })
  );
});

self.addEventListener('message', function(event) {
  var data = event.data || {};
  if (data.type === PURGE_MESSAGE_TYPE) {
    event.waitUntil(purgePublicCache(data.externalId));
  }
});

self.addEventListener('fetch', function(event) {
  var request = event.request;
  if (request.method !== 'GET') return;
  if (isAdminApiRequest(request.url)) return;
  if (isPublicApiRequest(request.url)) {
    networkFirst(event);
    return;
  }
  if (isStaticAsset(request.url)) {
    cacheFirst(event);
    return;
  }
});
`;
}
