import { generateServiceWorker } from './generateServiceWorker';

const config = {
  apiCacheName: 'public-survey-api-v2',
  staticCacheName: 'static-assets-v1',
  publicApiPathMatchers: ['/public/surveys/', '/public/questioner/'],
  purgeMessageType: 'PURGE_PUBLIC_CACHE',
};

describe('generateServiceWorker', () => {
  const sw = generateServiceWorker(config);

  it('ships network-first (the fix), NOT stale-while-revalidate (the bug)', () => {
    expect(sw).toContain('function networkFirst(event)');
    expect(sw).not.toContain('staleWhileRevalidate');
    expect(sw).not.toContain('MAX_CACHE_AGE_MS');
    expect(sw).not.toContain('isCacheFresh');
  });

  it('routes public API requests through networkFirst', () => {
    expect(sw).toContain('if (isPublicApiRequest(request.url)) {');
    expect(sw).toContain('networkFirst(event);');
  });

  it('embeds the configured cache names and matchers', () => {
    expect(sw).toContain('var API_CACHE = "public-survey-api-v2"');
    expect(sw).toContain('var STATIC_CACHE = "static-assets-v1"');
    expect(sw).toContain('"/public/surveys/"');
    expect(sw).toContain('"/public/questioner/"');
  });

  it('derives version-cleanup prefixes for the activate handler', () => {
    expect(sw).toContain('var API_CACHE_PREFIX = "public-survey-api-"');
    expect(sw).toContain('var STATIC_CACHE_PREFIX = "static-assets-"');
  });

  it('includes the purge message handler with the configured type', () => {
    expect(sw).toContain('var PURGE_MESSAGE_TYPE = "PURGE_PUBLIC_CACHE"');
    expect(sw).toContain('function purgePublicCache(externalId)');
    expect(sw).toContain('if (data.type === PURGE_MESSAGE_TYPE)');
  });

  it('takes control immediately (skipWaiting + clients.claim)', () => {
    expect(sw).toContain('self.skipWaiting();');
    expect(sw).toContain('self.clients.claim();');
  });

  it('never caches admin/auth API', () => {
    expect(sw).toContain('function isAdminApiRequest(url)');
    expect(sw).toContain("pathname.indexOf('/realms/')");
  });

  it('marks the file as generated to deter hand-edits', () => {
    expect(sw).toContain('GENERATED by @dloizides/pwa-sw');
  });

  it('defaults the purge message type when omitted', () => {
    const generated = generateServiceWorker({
      apiCacheName: 'a-v1',
      staticCacheName: 'b-v1',
      publicApiPathMatchers: ['/public/menus/'],
    });
    expect(generated).toContain('var PURGE_MESSAGE_TYPE = "PURGE_PUBLIC_CACHE"');
  });

  it('propagates config validation errors', () => {
    expect(() =>
      generateServiceWorker({ apiCacheName: '', staticCacheName: 'b', publicApiPathMatchers: ['/x/'] })
    ).toThrow();
  });
});
