import { generateServiceWorker } from './generateServiceWorker';

const config = {
  apiCacheName: 'public-survey-api-v2',
  staticCacheName: 'static-assets-v1',
  publicApiPathMatchers: ['/public/surveys/', '/public/questioner/'],
  purgeMessageType: 'PURGE_PUBLIC_CACHE',
};

describe('generateServiceWorker', () => {
  const sw = generateServiceWorker(config);

  it('ships network-first (the fix), NOT stale-while-revalidate (the bug)', () => {
    expect(sw).toContain('function networkFirst(event)');
    expect(sw).not.toContain('staleWhileRevalidate');
    expect(sw).not.toContain('MAX_CACHE_AGE_MS');
    expect(sw).not.toContain('isCacheFresh');
  });

  it('routes public API requests through networkFirst', () => {
    expect(sw).toContain('if (isPublicApiRequest(request.url)) {');
    expect(sw).toContain('networkFirst(event);');
  });

  it('embeds the configured cache names (suffixed with the build version) and matchers', () => {
    // The build version (default 'dev') is appended to the EFFECTIVE cache names so each build's
    // caches are distinct and the activate handler evicts every other build's.
    expect(sw).toContain('var API_CACHE = "public-survey-api-v2-dev"');
    expect(sw).toContain('var STATIC_CACHE = "static-assets-v1-dev"');
    expect(sw).toContain('"/public/surveys/"');
    expect(sw).toContain('"/public/questioner/"');
  });

  it('stamps the build version so each deploy ships a byte-different worker', () => {
    const a = generateServiceWorker({ ...config, buildVersion: 'abc123' });
    const b = generateServiceWorker({ ...config, buildVersion: 'def456' });
    expect(a).toContain('var BUILD_VERSION = "abc123"');
    expect(a).toContain('var API_CACHE = "public-survey-api-v2-abc123"');
    expect(a).not.toEqual(b); // different build → different bytes → the browser installs the update
  });

  it('derives version-cleanup prefixes for the activate handler', () => {
    expect(sw).toContain('var API_CACHE_PREFIX = "public-survey-api-"');
    expect(sw).toContain('var STATIC_CACHE_PREFIX = "static-assets-"');
  });

  it('includes the purge message handler with the configured type', () => {
    expect(sw).toContain('var PURGE_MESSAGE_TYPE = "PURGE_PUBLIC_CACHE"');
    expect(sw).toContain('function purgePublicCache(externalId)');
    expect(sw).toContain('if (data.type === PURGE_MESSAGE_TYPE)');
  });

  it('takes control immediately (skipWaiting + clients.claim)', () => {
    expect(sw).toContain('self.skipWaiting();');
    expect(sw).toContain('self.clients.claim();');
  });

  it('skips non-http(s) schemes (e.g. chrome-extension) before caching', () => {
    // The Cache API rejects cache.put for chrome-extension:/data: etc. — the fetch
    // handler must bail on any non-http(s) scheme so those pass through to the network.
    expect(sw).toContain('function isHttpRequest(url)');
    expect(sw).toContain("url.indexOf('http:') === 0");
    expect(sw).toContain("url.indexOf('https:') === 0");
    expect(sw).toContain('if (!isHttpRequest(request.url)) return;');
  });

  it('never caches admin/auth API', () => {
    expect(sw).toContain('function isAdminApiRequest(url)');
    expect(sw).toContain("pathname.indexOf('/realms/')");
  });

  it('marks the file as generated to deter hand-edits', () => {
    expect(sw).toContain('GENERATED by @dloizides/pwa-sw');
  });

  it('defaults the purge message type when omitted', () => {
    const generated = generateServiceWorker({
      apiCacheName: 'a-v1',
      staticCacheName: 'b-v1',
      publicApiPathMatchers: ['/public/menus/'],
    });
    expect(generated).toContain('var PURGE_MESSAGE_TYPE = "PURGE_PUBLIC_CACHE"');
  });

  it('propagates config validation errors', () => {
    expect(() =>
      generateServiceWorker({ apiCacheName: '', staticCacheName: 'b', publicApiPathMatchers: ['/x/'] })
    ).toThrow();
  });
});
