import { cachePrefix, resolveConfig, type ServiceWorkerConfig } from './config';
import { VERSION_REPLY_TYPE, VERSION_REQUEST_TYPE } from './freshness';

/** The pathname of a URL given as a path or as an absolute URL. */
function pathOf(url: string): string {
  return /^https?:/.test(url) ? new URL(url).pathname : url;
}

/**
 * Generate the source of a PWA service worker (`service-worker.js`) from config.
 *
 * The emitted SW implements the FIXED caching model (the one katalogos-web
 * converged on after the 2026-06-11 stale-menu fix):
 * - Public API reads: NETWORK-FIRST — always fetch fresh when online; the cached
 *   copy is only an offline fallback. This guarantees an edit/activation is
 *   reflected on the next load for every visitor (the old stale-while-revalidate
 *   served up to a day-old payload).
 * - HTML navigations + unhashed static assets: network-first (revalidated).
 * - Content-hashed static assets: cache-first.
 * - Admin/auth API: network-only (never cached).
 * - A `{ type: <purgeMessageType>, externalId? }` message evicts cached public
 *   responses immediately (so an editor preview refreshes mid-session).
 * - Cache names are versioned; the activate handler deletes prefix-matching old
 *   versions so bumping the version evicts stale entries on deploy.
 *
 * The output is a plain ES5-style worker string with no imports — safe to write
 * straight into an app's `public/service-worker.js`.
 */
export function generateServiceWorker(config: ServiceWorkerConfig): string {
  const resolved = resolveConfig(config);
  const apiPrefix = cachePrefix(resolved.apiCacheName);
  const staticPrefix = cachePrefix(resolved.staticCacheName);
  // The EFFECTIVE cache names are now derived IN the emitted worker, as
  // `<cacheName> + "-" + BUILD_VERSION`, rather than pre-joined here. Same value,
  // two gains: BUILD_VERSION is genuinely referenced (it was a stamped-but-unused
  // const, which every consumer's `no-unused-vars` flagged), and the version can
  // no longer drift away from the cache names -- they were three independent
  // interpolations of the same field, agreeing only by convention.
  //
  // The PREFIXES stay the bare config names so the activate handler still evicts
  // every OTHER build's caches. Note cachePrefix() also strips the -vN schema
  // segment, so prefix + BUILD_VERSION is NOT the cache name -- do not "simplify"
  // the emitted lines to use the prefixes.

  const json = (value: unknown): string => JSON.stringify(value);
  const bypassPaths = [pathOf(resolved.swUrl), pathOf(resolved.registrationUrl)];

  return `/**
 * Service Worker — GENERATED by @dloizides/pwa-sw. DO NOT EDIT BY HAND.
 * Regenerate via the app's "generate:sw" script (config: pwa-sw.config.js).
 *
 * Caching strategies:
 * - Public API reads (network-first): always fresh when online; cache is an
 *   offline fallback only — so an edit/activation shows on the next load.
 * - HTML navigations + unhashed static assets (network-first, revalidated).
 * - Content-hashed static assets (cache-first).
 * - Admin/auth API (network-only, never cached).
 * Cache names are versioned; bumping a version evicts the old (stale) cache on
 * activation. A "${resolved.purgeMessageType}" message evicts the public cache
 * immediately for same-session freshness.
 *
 * BUILD_VERSION is stamped per build so every deploy ships a byte-different worker
 * — the browser only fetches/installs a new SW when this file's bytes change, so
 * this is what lets an already-open tab pick up a new release (auto-update).
 */
const BUILD_VERSION = ${json(resolved.buildVersion)};

const API_CACHE = ${json(resolved.apiCacheName)} + "-" + BUILD_VERSION;
const STATIC_CACHE = ${json(resolved.staticCacheName)} + "-" + BUILD_VERSION;
const MANAGED_CACHES = [API_CACHE, STATIC_CACHE];
const API_CACHE_PREFIX = ${json(apiPrefix)};
const STATIC_CACHE_PREFIX = ${json(staticPrefix)};
const PUBLIC_API_MATCHERS = ${json(resolved.publicApiPathMatchers)};
const STATIC_EXTENSIONS = ${json(resolved.staticExtensions)};
const PURGE_MESSAGE_TYPE = ${json(resolved.purgeMessageType)};
const FRESH_UNHASHED_ASSETS = ${json(resolved.freshUnhashedAssets)};
const HASHED_ASSET_PATTERN = new RegExp(${json(resolved.hashedAssetPattern)});
const UNHASHED_PATH_MATCHERS = ${json(resolved.unhashedPathMatchers)};
const BYPASS_PATHS = ${json(bypassPaths)};
const SHELL_URL = ${json(resolved.scope)};
const VERSION_REQUEST_TYPE = ${json(VERSION_REQUEST_TYPE)};
const VERSION_REPLY_TYPE = ${json(VERSION_REPLY_TYPE)};

/**
 * The worker script and its registration snippet always come from the network:
 * a cached copy of either is how a zombie build outlives a deploy.
 */
function isBypassed(url) {
  return BYPASS_PATHS.indexOf(new URL(url).pathname) !== -1;
}

/** A page load: a navigation, or a request that accepts HTML. */
function isHtmlRequest(request) {
  if (request.mode === 'navigate') return true;
  const accept = request.headers && request.headers.get ? request.headers.get('accept') : null;
  return !!accept && accept.indexOf('text/html') !== -1;
}

/** An asset whose URL stays the same across builds (no content hash in the filename). */
function isUnhashedAsset(url) {
  const pathname = new URL(url).pathname;
  for (let i = 0; i < UNHASHED_PATH_MATCHERS.length; i++) {
    if (pathname.indexOf(UNHASHED_PATH_MATCHERS[i]) !== -1) return true;
  }
  return !HASHED_ASSET_PATTERN.test(pathname.slice(pathname.lastIndexOf('/') + 1));
}

/** A cacheable public API read (network-first) if its pathname matches any matcher. */
function isPublicApiRequest(url) {
  const pathname = new URL(url).pathname;
  for (let i = 0; i < PUBLIC_API_MATCHERS.length; i++) {
    if (pathname.indexOf(PUBLIC_API_MATCHERS[i]) !== -1) return true;
  }
  return false;
}

/** An admin/protected/auth request that must never be cached. */
function isAdminApiRequest(url) {
  const pathname = new URL(url).pathname;
  if (pathname.indexOf('/api/') !== -1 && pathname.indexOf('/public/') === -1) return true;
  if (pathname.indexOf('/realms/') !== -1 || pathname.indexOf('/token') !== -1) return true;
  return false;
}

/**
 * A cacheable request over a supported scheme. The Cache API only accepts
 * http/https — a chrome-extension:, safari-extension:, data: or other-scheme
 * request throws on cache.put ("Request scheme '...' is unsupported"), so those
 * must skip the SW entirely and pass through to the network.
 */
function isHttpRequest(url) {
  return url.indexOf('http:') === 0 || url.indexOf('https:') === 0;
}

/** A static asset (cache-first) based on file extension. */
function isStaticAsset(url) {
  const pathname = new URL(url).pathname.toLowerCase();
  for (let i = 0; i < STATIC_EXTENSIONS.length; i++) {
    if (pathname.lastIndexOf(STATIC_EXTENSIONS[i]) === pathname.length - STATIC_EXTENSIONS[i].length) return true;
  }
  return false;
}

/**
 * Network-first for public API: always try the network so edits show
 * immediately; cache successful responses for offline; only fall back to the
 * cached copy when the network fails.
 */
function networkFirst(event) {
  event.respondWith(
    caches.open(API_CACHE).then(function(cache) {
      return fetch(event.request).then(function(networkResponse) {
        if (networkResponse && networkResponse.ok) {
          const responseToCache = networkResponse.clone();
          const headers = new Headers(responseToCache.headers);
          headers.set('sw-cached-at', new Date().toISOString());
          return responseToCache.blob().then(function(body) {
            cache.put(event.request, new Response(body, {
              status: responseToCache.status,
              statusText: responseToCache.statusText,
              headers: headers,
            }));
            return networkResponse;
          });
        }
        return networkResponse;
      }).catch(function() {
        return cache.match(event.request);
      });
    })
  );
}

/**
 * Network-first for HTML navigations and unhashed assets: the network copy wins
 * whenever it is reachable, the per-build cache is only the offline fallback
 * (for a page: its cached copy, else the cached app shell at the scope root).
 */
function networkFirstStatic(event, fetchInit, fallbackUrl) {
  event.respondWith(
    caches.open(STATIC_CACHE).then(function(cache) {
      return fetch(event.request, fetchInit).then(function(networkResponse) {
        if (networkResponse && networkResponse.ok) {
          cache.put(event.request, networkResponse.clone());
        }
        return networkResponse;
      }).catch(function() {
        return cache.match(event.request).then(function(cached) {
          if (cached || !fallbackUrl) return cached;
          return cache.match(fallbackUrl);
        });
      });
    })
  );
}

/** Cache-first for content-hashed static assets. */
function cacheFirst(event) {
  event.respondWith(
    caches.open(STATIC_CACHE).then(function(cache) {
      return cache.match(event.request).then(function(cachedResponse) {
        if (cachedResponse) return cachedResponse;
        return fetch(event.request).then(function(networkResponse) {
          if (networkResponse && networkResponse.ok) {
            cache.put(event.request, networkResponse.clone());
          }
          return networkResponse;
        });
      });
    })
  );
}

/**
 * Evict cached public-API responses. With no externalId, drops the whole API
 * cache; with one, only entries whose URL contains that id.
 */
function purgePublicCache(externalId) {
  return caches.open(API_CACHE).then(function(cache) {
    if (!externalId) {
      return caches.delete(API_CACHE);
    }
    return cache.keys().then(function(requests) {
      return Promise.all(
        requests
          .filter(function(request) { return request.url.indexOf(externalId) !== -1; })
          .map(function(request) { return cache.delete(request); })
      );
    });
  });
}

// --- Lifecycle ---

self.addEventListener('install', function() {
  self.skipWaiting();
});

self.addEventListener('activate', function(event) {
  event.waitUntil(
    caches.keys().then(function(cacheNames) {
      return Promise.all(
        cacheNames
          .filter(function(name) {
            const isOurCache = name.indexOf(API_CACHE_PREFIX) === 0 || name.indexOf(STATIC_CACHE_PREFIX) === 0;
            const isCurrent = MANAGED_CACHES.indexOf(name) !== -1;
            return isOurCache && !isCurrent;
          })
          .map(function(name) { return caches.delete(name); })
      );
    }).then(function() {
      return self.clients.claim();
    })
  );
});

self.addEventListener('message', function(event) {
  const data = event.data || {};
  if (data.type === PURGE_MESSAGE_TYPE) {
    event.waitUntil(purgePublicCache(data.externalId));
  }
  if (data.type === VERSION_REQUEST_TYPE) {
    const reply = { type: VERSION_REPLY_TYPE, version: BUILD_VERSION };
    if (event.ports && event.ports[0]) event.ports[0].postMessage(reply);
    else if (event.source) event.source.postMessage(reply);
  }
});

self.addEventListener('fetch', function(event) {
  const request = event.request;
  if (request.method !== 'GET') return;
  if (!isHttpRequest(request.url)) return;
  if (isBypassed(request.url)) return;
  if (isAdminApiRequest(request.url)) return;
  if (isHtmlRequest(request)) {
    networkFirstStatic(event, undefined, SHELL_URL);
    return;
  }
  if (isPublicApiRequest(request.url)) {
    networkFirst(event);
    return;
  }
  if (!isStaticAsset(request.url)) return;
  if (FRESH_UNHASHED_ASSETS && isUnhashedAsset(request.url)) {
    networkFirstStatic(event, { cache: 'no-cache' });
    return;
  }
  cacheFirst(event);
});
`;
}
