import { generateRegistration } from './generateRegistration';

const config = {
  apiCacheName: 'aml-public-api-v1',
  staticCacheName: 'aml-static-assets-v1',
  publicApiPathMatchers: ['/v1/pep-coverage'],
  scope: '/app/',
  updateCheckIntervalMs: 30000,
};

describe('generateRegistration', () => {
  const reg = generateRegistration(config);

  it('marks the file as generated to deter hand-edits', () => {
    expect(reg).toContain('GENERATED by @dloizides/pwa-sw');
  });

  it('registers the SW under the configured scope + derived url, with updateViaCache none', () => {
    expect(reg).toContain('var SCOPE = "/app/"');
    expect(reg).toContain('var SW_URL = "/app/service-worker.js"'); // derived from scope
    expect(reg).toContain("updateViaCache: 'none'");
  });

  it('honours an explicit swUrl over the derived one', () => {
    const r = generateRegistration({ ...config, swUrl: '/custom/sw.js' });
    expect(r).toContain('var SW_URL = "/custom/sw.js"');
  });

  it('proactively checks for updates on load, on the interval, and on refocus', () => {
    expect(reg).toContain('reg.update()');
    expect(reg).toContain('var UPDATE_INTERVAL_MS = 30000');
    expect(reg).toContain('setInterval(check, UPDATE_INTERVAL_MS)');
    expect(reg).toContain("document.addEventListener('visibilitychange'");
  });

  it('reloads once when a NEW worker takes control, guarded against first-install + loops', () => {
    expect(reg).toContain("navigator.serviceWorker.addEventListener('controllerchange'");
    expect(reg).toContain('window.location.reload();');
    expect(reg).toContain('var hadController = !!navigator.serviceWorker.controller;'); // skip first install
    expect(reg).toContain('if (refreshing) return;'); // idempotent — no reload loop
  });

  it('omits the interval timer when updateCheckIntervalMs is 0', () => {
    const r = generateRegistration({ ...config, updateCheckIntervalMs: 0 });
    expect(r).toContain('var UPDATE_INTERVAL_MS = 0');
    // The setInterval is guarded by `if (UPDATE_INTERVAL_MS > 0)`, so with 0 it never schedules.
    expect(r).toContain('if (UPDATE_INTERVAL_MS > 0)');
  });

  it('defaults scope to / and derives the sw url when scope is omitted', () => {
    const r = generateRegistration({
      apiCacheName: 'a-v1',
      staticCacheName: 'b-v1',
      publicApiPathMatchers: ['/public/'],
    });
    expect(r).toContain('var SCOPE = "/"');
    expect(r).toContain('var SW_URL = "/service-worker.js"');
    expect(r).toContain('var UPDATE_INTERVAL_MS = 60000'); // default interval
  });
});
