import { resolveConfig, type ServiceWorkerConfig } from './config';

/**
 * Generate the source of the SW REGISTRATION snippet (`sw-register.js`) — the
 * counterpart to {@link generateServiceWorker}. Shipped as a static file and
 * referenced by a `<script src>` in the app's HTML (Expo's static export strips
 * runtime `<script>` from `+html.tsx`, so a served file is the portable shape).
 *
 * It makes a deployed app AUTO-UPDATE — the fix for the class of bug where a
 * redeploy left an already-open PWA tab (or a soft SPA navigation) running the
 * OLD code until the user manually cleared the service worker:
 * - registers with `updateViaCache: 'none'` so the browser never HTTP-caches the
 *   SW file itself (it must re-fetch it to notice the per-build byte change),
 * - proactively checks for a new version on load, on a cadence, and whenever the
 *   tab is refocused (so a long-open tab converges on the latest release),
 * - reloads the page ONCE when a NEW worker takes control (`controllerchange`),
 *   guarded so the FIRST install on a fresh visit never triggers a reload and a
 *   reload can never loop.
 *
 * The generated SW does `skipWaiting()` on install + `clients.claim()` on
 * activate, so a newly-installed worker takes control immediately — which is what
 * fires the `controllerchange` this snippet listens for.
 *
 * Output is a plain ES5-style IIFE with no imports — safe to write straight into
 * an app's `public/sw-register.js`.
 */
export function generateRegistration(config: ServiceWorkerConfig): string {
  const resolved = resolveConfig(config);
  const json = (value: unknown): string => JSON.stringify(value);

  return `/**
 * PWA service-worker registration — GENERATED by @dloizides/pwa-sw. DO NOT EDIT BY HAND.
 * Regenerate via the app's "generate:sw" script (config: pwa-sw.config.js).
 *
 * Auto-updates the app: checks for a new worker on load / on a cadence / on
 * refocus, and reloads once when a new worker takes control, so a redeploy is
 * picked up without the user clearing anything.
 */
(function () {
  if (!('serviceWorker' in navigator)) return;

  var SW_URL = ${json(resolved.swUrl)};
  var SCOPE = ${json(resolved.scope)};
  var UPDATE_INTERVAL_MS = ${resolved.updateCheckIntervalMs};

  // Reload ONCE when a new worker takes control (an update landed). The first
  // controllerchange on a fresh visit is the initial install, not an update —
  // don't reload for that one; only reload for a genuine hand-off after we were
  // already controlled. The 'refreshing' guard makes the reload idempotent.
  var hadController = !!navigator.serviceWorker.controller;
  var refreshing = false;
  navigator.serviceWorker.addEventListener('controllerchange', function () {
    if (!hadController) { hadController = true; return; }
    if (refreshing) return;
    refreshing = true;
    window.location.reload();
  });

  window.addEventListener('load', function () {
    var start = function () {
      navigator.serviceWorker
        .register(SW_URL, { scope: SCOPE, updateViaCache: 'none' })
        .then(function (reg) {
          var check = function () { try { reg.update(); } catch (e) {} };
          check(); // look for a newer worker right away
          if (UPDATE_INTERVAL_MS > 0) {
            setInterval(check, UPDATE_INTERVAL_MS);
          }
          document.addEventListener('visibilitychange', function () {
            if (document.visibilityState === 'visible') check();
          });
        })
        .catch(function (err) {
          // eslint-disable-next-line no-console
          console.warn('SW registration failed', err);
        });
    };
    // Defer to idle so registration never blocks first paint.
    if (typeof requestIdleCallback !== 'undefined') {
      requestIdleCallback(start);
    } else {
      setTimeout(start, 0);
    }
  });
})();
`;
}
