import { resolveConfig, type ServiceWorkerConfig } from './config';

export interface RetireWorkerFile {
  /** Path relative to the output directory (the directory served at `scope`). */
  file: string;
  source: string;
}

const SAFE_WORKER_PATH = /^\/(?:[\w.-]+\/)*[\w.-]+\.js$/;

/**
 * Source of a kill-switch worker, served at a RETIRED worker URL. The browser's
 * update check for that URL installs it over the old worker; it takes over at
 * once, deletes every cache, unregisters itself and navigates each window it
 * controls once, so the page reloads from the network with no worker.
 */
export function generateRetireWorker(): string {
  return `/* Generated by @dloizides/pwa-sw -- kill-switch for a retired service-worker URL. Do not edit. */
self.addEventListener('install', function () {
  self.skipWaiting();
});

self.addEventListener('activate', function (event) {
  event.waitUntil(
    caches.keys()
      .then(function (names) { return Promise.all(names.map(function (n) { return caches.delete(n); })); })
      .then(function () { return self.registration.unregister(); })
      .then(function () { return self.clients.matchAll({ type: 'window' }); })
      .then(function (clients) {
        return Promise.all(clients.map(function (client) {
          return client.navigate(client.url).catch(function () { return undefined; });
        }));
      })
  );
});
`;
}

function relativeToScope(url: string, scope: string, live: string[]): string {
  if (!SAFE_WORKER_PATH.test(url) || url.split('/').includes('..')) {
    throw new Error(`pwa-sw: retireWorkerUrls entry must be an absolute .js path: ${url}`);
  }
  if (live.includes(url)) {
    throw new Error(`pwa-sw: retireWorkerUrls entry is the live worker or registration URL: ${url}`);
  }
  const root = scope.endsWith('/') ? scope : scope + '/';
  if (!url.startsWith(root)) {
    throw new Error(`pwa-sw: retireWorkerUrls entry ${url} is outside scope ${root}`);
  }
  return url.slice(root.length);
}

/** One kill-switch file per `retireWorkerUrls` entry, validated against the live URLs. */
export function retireWorkerFiles(config: ServiceWorkerConfig): RetireWorkerFile[] {
  const urls = config.retireWorkerUrls ?? [];
  if (urls.length === 0) {
    return [];
  }
  const resolved = resolveConfig(config);
  const live = [resolved.swUrl, resolved.registrationUrl];
  const source = generateRetireWorker();
  return urls.map((url) => ({ file: relativeToScope(url.trim(), resolved.scope, live), source }));
}
